calais_entities=['Anniversary','City','Company','Continent','Country','Currency','EmailAddress','EntertainmentAwardEvent','Facility','FaxNumber','Holiday','IndustryTerm','MarketIndex','MedicalCondition','MedicalTreatment','Movie','MusicAlbum','MusicGroup','NaturalFeature','OperatingSystem','Organization','Person','PhoneNumber','PoliticalEvent','Position','Product','ProgrammingLanguage','ProvinceOrState','PublishedMedium','RadioProgram','RadioStation','Region','SportsEvent','SportsGame','SportsLeague','Technology','TVShow','TVStation','URL']
filter_entities=['City','Company','Continent','Country','Currency','EntertainmentAwardEvent','Facility','Holiday','IndustryTerm','MarketIndex','MedicalCondition','MedicalTreatment','Movie','MusicAlbum','MusicGroup','NaturalFeature','OperatingSystem','Organization','Person', 'PoliticalEvent','Position','Product','ProgrammingLanguage','ProvinceOrState','PublishedMedium','RadioProgram','RadioStation','Region', 'SportsEvent','SportsGame','SportsLeague','Technology','TVShow','TVStation']

calais_events=['Acquisition','Alliance','AnalystEarningsEstimate','AnalystRecommendation','ArmedAttack','ArmsPurchaseSale','Arrest','Bankruptcy','BonusSharesIssuance','BusinessRelation','Buybacks','CandidatePosition','CompanyAccountingChange','CompanyAffiliates','CompanyCompetitor','CompanyCustomer','CompanyEarningsAnnouncement','CompanyEarningsGuidance','CompanyEmployeesNumber','CompanyExpansion','CompanyForceMajeure','CompanyFounded','CompanyInvestment','CompanyLaborIssues','CompanyLayoffs','CompanyLegalIssues','CompanyListingChange','CompanyLocation','CompanyMeeting','CompanyNameChange','CompanyProduct','CompanyReorganization','CompanyRestatement','CompanyTechnology','CompanyTicker','CompanyUsingProduct','ConferenceCall','Conviction','CreditRating','DebtFinancing','DelayedFiling','DiplomaticRelations','Dividend','EmploymentChange','EmploymentRelation','EnvironmentalIssue','EquityFinancing','Extinction','FamilyRelation','FDAPhase','IndicesChanges','Indictment','IPO','JointVenture','ManMadeDisaster','Merger','MilitaryAction','MovieRelease','MusicAlbumRelease','NaturalDisaster','PatentFiling','PatentIssuance','PersonAttributes','PersonCareer','PersonCommunication','PersonEducation','PersonEmailAddress','PersonLocation','PersonParty','PersonRelation','PersonTravel','PoliticalEndorsement','PoliticalRelationship','PollsResult','ProductIssues','ProductRecall','ProductRelease','Quotation','SecondaryIssuance','StockSplit','Trial','VotingResult']
filter_events=['Acquisition','Alliance','AnalystEarningsEstimate','AnalystRecommendation','ArmedAttack','ArmsPurchaseSale', 'Arrest','Bankruptcy','BonusSharesIssuance','BusinessRelation','Buybacks','CandidatePosition', 'CompanyAccountingChange','CompanyAffiliates','CompanyCompetitor','CompanyCustomer','CompanyEarningsAnnouncement','CompanyEarningsGuidance','CompanyEmployeesNumber','CompanyExpansion','CompanyForceMajeure','CompanyFounded','CompanyInvestment','CompanyLaborIssues','CompanyLayoffs','CompanyLegalIssues','CompanyListingChange','CompanyLocation','CompanyMeeting','CompanyNameChange','CompanyProduct','CompanyReorganization','CompanyRestatement','CompanyTechnology','CompanyTicker','CompanyUsingProduct','ConferenceCall','Conviction','CreditRating','DebtFinancing','DelayedFiling','DiplomaticRelations','Dividend','EmploymentChange','EmploymentRelation','EnvironmentalIssue','EquityFinancing','Extinction','FamilyRelation','FDAPhase','IndicesChanges','Indictment','IPO','JointVenture', 'ManMadeDisaster','Merger','MilitaryAction','MovieRelease','MusicAlbumRelease','NaturalDisaster','PatentFiling','PatentIssuance','PersonAttributes','PersonCareer','PersonCommunication','PersonEducation','PersonLocation','PersonParty','PersonRelation','PersonTravel','PoliticalEndorsement', 'PoliticalRelationship','PollsResult','ProductIssues','ProductRecall','ProductRelease','Quotation','SecondaryIssuance','StockSplit','Trial','VotingResult']

for type in calais_entities:
    if type not in filter_entities:
        print type

print "\nevents\n"
for type in calais_events:
    if type not in filter_events:
        print type
